# this file is taken only on runner
# full test is ran, like `npm test`
# ---------------------------------
app: 
  docs: false
  logging: true # for logging stuffs out
  morgan: false # for request logging
  port: 7000
  
mails:
  enable: false

database:
  url: mongodb://192.168.1.9:27017/default-testDB